### PR TITLE
fix: Make sure generated projectile ID's are unique

### LINKED ISSUE #238: Using global rand functions can have bad results if the user attempts to use `seed(...)`
`NetworkWeapon._generate_id(...)` calls `randi_range(...)` for selecting random characters. This would normally be fine, but if a user attempts to use `seed(...)` to intentionally generate the same random values all peers it'll end up re-using the same values.

Using a `RandomNumberGenerator` (initialized with `randomize()`) to always maintain a seed unique from others' code and expectations is recommended (also for the user, so this is half on me :wink:).

### PR DESCRIPTION
**Pull request by elementbound**
Fixes #238

### CODE REVIEW

**Comment by Lexari0** [comment]
Ideally, the RNG should be seeded with the same value for all peers as it would guarantee they generate the same IDs in the same order.

This would give some guarantee to ID uniqueness (in fact if we generate a used ID something has gone very wrong) while also giving some more server validation possibilities (eg: server would also generate an ID when a weapon is fired and it should match).

That all being said, I'm not sure how much of a refactor that would take and I'm definitely not going to be the type to demand things be done my preferred way on someone else's project. This is already a very good improvement :)

**Comment by TheYellowArchitect** [comment]
Seeing https://zelark.github.io/nano-id-cc/ with 12 characters, you would need 9 000 000 000 projectiles for one to have 1% to conflict another. So I think doing a check isn't required - after all, that is why such a long string is used: In order to avoid comparing ID with other projectiles. If you compare with existing IDs, may as well use a normal integer-based ID system.

I suggest instead making the 12 characters a project setting variable, but honestly, 12 is good as it is, there are no practical chances for collisions. I would argue this PR is needless.

**Comment by elementbound** [comment]
@Lexari0 
> That all being said, I'm not sure how much of a refactor that would take and I'm definitely not going to be the type to demand things be done my preferred way on someone else's project. This is already a very good improvement :)

Appreciated :) I also want to understand your POV, especially on this:

> Ideally, the RNG should be seeded with the same value for all peers as it would guarantee they generate the same IDs in the same order.

The idea is to generate an ID that is unique across projectiles and _peers_. The point is to avoid generating the same ID, so whenever someone requests a projectile, they don't request it the same ID as anyone else would. 

I wonder if there's something about the codebase / approach that suggests matching ID's?

**Comment by elementbound** [comment]
@TheYellowArchitect sure, check removed

**Comment by elementbound** [comment]
Merged as I didn't want to keep this fix waiting for longer, but I'm still up for discussion here.

**Pull request merged**
