### PR TITLE
Simplified Type interpolators

### PR DESCRIPTION
**Pull request by TheYellowArchitect**
Solves https://github.com/foxssake/netfox/issues/257

### CODE REVIEW

**Comment by annamaria-szentpeteri** [comment]
New implementation removes the ability from the user to overwrite interpolation for existing types and also removes ability to register interpolation for user defined types.

This is a loss in functionality and flexibility.

**Comment by TheYellowArchitect** [comment]
>New implementation removes the ability from the user to overwrite interpolation for existing types and also removes ability to register interpolation for user defined types.

Could you give me an example of this in the version of the master branch?

**Comment by annamaria-szentpeteri** [comment]
The code you refactored clearly documents this functionality: [addons/netfox/interpolators.gd line 24-26 ](https://github.com/foxssake/netfox/blob/d3c70d317534b11f17c7b8f3507532d848200c64/addons/netfox/interpolators.gd#L24)

```
## Register an interpolator.
##
## New interpolators are pushed to the front of the list, making them have 
## precedence over existing ones. This can be useful in case you want to override
## the built-in interpolators.
static func register(is_applicable: Callable, apply: Callable):
	interpolators.push_front(Interpolator.make(is_applicable, apply))
```

Your solution is not flexible enough to replicate this behaviour. You removed the following features:

- Adding interpolation overwrite for types that has registration in Interpolators
- Adding interpolation for types not registered in Interpolators

Why remove this functionality?

**Comment by TheYellowArchitect** [comment]
The condition is practically always a type condition `a is float`, so having a full `if (condition)` there is bloated imo, also even though I write GDscript for a year now, I haven't stumbled into that kind of lambda function, so new users will definitely not use it either.

And 2 callables (aka function pointers) as parameters for a lerp function is overengineering.

You can still make your own interpolator, no one stops you lol
I would argue it's cleaner to make it with the current code, or make your own class entirely. Anyway, if @elementbound thinks the same, feel free to close this PR.

Though it does say a lot that you haven't posted a code example of an interpolator you overwrote or added

**Comment by TheYellowArchitect** [comment]
As mentioned by @annamaria-szentpeteri this PR doesn't cover overwriting interpolators of existing types, for different lerps, e.g. different curves (so the weight can be the same, but the output is different), so I convert it to draft until I think of a possible pivot of this PR instead of closing it

**Comment by annamaria-szentpeteri** [comment]
Okay, you can stop right there.

> no one stops you lol

> Though it does say a lot that you haven't posted a code example of an interpolator you overwrote or added

PRs are not for this kind of behaviour. Please take a look at how you communicate with others.


So bottom line is: you removed functionality from a part of the library that can be used by others. Justification is that it is not needed or rather this library should not provide this in your opinion. That is fine, code owner can decide how he wants to proceed.

**Comment by TheYellowArchitect** [comment]
Overwriting Vector2 interpolations with cubic interpolation before this PR:
```gdscript
Interpolators.register(
	func(a): return a is Vector2,
	func(a: Vector2, b: Vector2, c: Vector2, d: Vector2, f: float): return a.cubic_interpolate(b, c, d, f)
)
```
Note that on adding the above Vector2 interpolation, all Vector2s in the entire game are now converted to cubic interpolation, instead of a normal lerp, which I would consider this impractical, so I guess devs will just make their own lerp, but that's just my assumption

To make the above lerp overwrite in this PR, you just replace this line
```gdscript
TYPE_VECTOR2:
			return interpolate_vector2(a as Vector2, b as Vector2, f)
```
with this
```gdscript
TYPE_VECTOR2:
			return (a as Vector2).cubic_interpolate(b as Vector2, c as Vector2, d as Vector2, f)
```

Still the same problem, as mentioned above, so better make that kind of interpolator a function in the local class it is needed, so it doesn't overwrite its type. Given lerps are one-liners, no real problem.
Anyway, there is also another problem I noticed in this PR. The `< 0.5` condition isn't covered, in case the user places an entire custom class in the parameter (hey, maybe you made a Vector6 :laughing: )
And given this PR only increases performance and readability in a **helper class**, instead of adding a new feature, and I would also have to rewrite documentation, @elementbound feel free to close this PR.

**Comment by annamaria-szentpeteri** [comment]
Extra info for this part:

> Especially when you see tick-interpolator.gd where you cache these interpolators in a dictionary...

[tick-interpolator documentation](https://github.com/foxssake/netfox/blob/main/docs/netfox/nodes/tick-interpolator.md#changing-configuration) explains that you should call `process_settings()` every time interpolated properties change. Caching helps with performance, because you don't have to call `Interpolators.find_for(property.get_value())` within each `_interpolate()` (which is called from `_process()`).

@elementbound could it be beneficial to add the documentation that if you register a new interpolation into Interpolators, the `process_settings()` should be called after the registration? Or is it meant to be self-explanatory by how the library should be used?

**Pull request closed without merging**
